$schema: "http://json-schema.org/draft-07/schema#"
description: Schema for genome list CSV file
type: object
properties:
  genome_id:
    type: string
    description: Unique genome identifier
  genome_path:
    type: string
    description: Path to the genome file (.fna assembly file or directory with Bakta results)
  genome_type:
    type: string
    description: Type of the genome file (fna or bakta_dir)
    enum: ["fna", "bakta_dir"]
required:
  - genome_id
  - genome_path
  - genome_type 